### ISSUE TITLE
Permission issues with datalad remove and datalad drop in dataset hierarchy

### ISSUE THREAD

**Issue by adswa** [psychoinformatics-de/knowledge-base#32] opened 2023-04-21 08:11 UTC
> The information in this issue will be public. If the support event occurred on a private channel, do not include identifying information without explicit consent!

Origin: Neurostars, April 20th: https://neurostars.org/t/permission-issues-with-datalad-remove-and-datalad-drop/25616

A user reports PermissionDenied errors for some subdatasets in a dataset hierarchy that many people operate in, and inexplainable ``notneeded`` results for ``datalad drop``. So far, the exact nature of the issue isn't yet clear, but clarifying questions have been asked. 

TODO (not necessarily to be performed in this order)
- [x] Inform OP/Add reference to this issue at origin
- [x] Clarifying Qs asked or not needed
- [ ] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by christian-monch** [comment] 2023-05-04 13:23
OP has inquired about the progress.

**Comment by loj** [comment] 2023-05-05 13:42
It's still unclear to me what the problem is here. If I understand correctly, the current situation is that the user was able to drop files within the subdataset, and has added subdataset as a safe directory. But they are still unable to remove the subdataset (getting the same permission error `[ERROR ] [Errno 1] Operation not permitted: '/data/proj_bitter-reward/firstlevel' (PermissionError)`).

Perhaps the superdataset needs to be declared as a safe directory?

**Comment by mih** [comment] 2023-05-08 10:57
@christian-monch the link to this issue you likely wanted to post in https://neurostars.org/t/permission-issues-with-datalad-remove-and-datalad-drop/25616/7 is actually not pointing here. I cannot fix that myself.

**Comment by christian-monch** [comment] 2023-05-11 14:58
> @christian-monch the link to this issue you likely wanted to post in https://neurostars.org/t/permission-issues-with-datalad-remove-and-datalad-drop/25616/7 is actually not pointing here. I cannot fix that myself.

Thanks, I posted it also on neurostars.

**Comment by loj** [comment] 2023-07-31 10:54
OP was directed to office hours for a live debugging session back in May. As far as I am aware, they haven't stopped by yet.

Since we don't have any further insight into what the problem is, I will close this for now. It can be re-opened if we come across similar reports or get new info from OP.

**Comment by adswa** [comment] 2023-09-05 14:20
I'm posting an update from the office hour:

![image](https://github.com/psychoinformatics-de/knowledge-base/assets/29738718/e58ce473-c9a2-4c0d-a889-fb8b752ff1f9)

**Comment by adswa** [comment] 2023-09-05 14:29
@christian-monch suggested running ``setfacl -m "u:<...>:rwx" firstlevel``. This initially failed with a permission denied Error, but the user had sudo privileges and ran the command successfully as root. Nevertheless, ``chmod u+rw firstlevel`` yielded a permission denied error.

**Comment by adswa** [comment] 2023-09-05 14:34
The issue was finally resolved after repeating ``sudo chmod -R ...``, which finally made drop/remove succeed. Feels slightly unsatisfactory if it needs sudo, but its at least a success :tada: - if someone has more insights on ACLs we were missing, please share :)

**Comment by jsheunis** [comment] 2023-09-05 14:45
Summary after initial inspection:

- user's server user can not get read+write permissions for subdataset directory, most likely because of access control list (as derived from `+` at end of permission characters in `ls -l` output)
- Multiple people can do things in that the same folder on the server
- There exists potential that one of the subdatasets can be configured not for shared access
- If a user pushed into such a location, git annex's default setup would prevent other users from doing the same

Some things we tried:
- `chmod u+wr firstlevel ` operation not permitted
- `setfacl -m "u:<...>:rwx" firstlevel` operation not permitted
- `sudo setfacl -m "u:<...>:rwx" firstlevel` command does not fail, but afterwords `chmod...` has the same outcome.

Interim discussion:
- `rm -rf` goes down in the hierarchy first, then deletes from the bottom up, and might cripple the tree if there are other directories also with permission issues. As opposed to datalad drop which executes the process only after doing the necessary checks on all levels of the hierarchy and preventing such a crippled result.

Finally:
- change owner: `sudo chown -R <username> firstlevel`  this runs without an issue
- `datalad remove` -> success!!

**Closed** 2023-09-11 13:17 UTC
Labels: support-tracker, via-neurostars
