### ISSUE TITLE
How to ignore a subdataset to not slow down operations?

### ISSUE THREAD

**Issue by bpoldrack** [psychoinformatics-de/knowledge-base#13] opened 2023-04-12 09:39 UTC
Origin: https://neurostars.org/t/turning-subdataset-into-subdirectory-that-is-gitignored/24980

TODO (not necessarily to be performed in this order)
- [ ] Inform OP/Add reference to this issue at origin
- [ ] Clarifying Qs asked or not needed
- [ ] Nature of the issue is understood
- [ ] Inform OP about resolution

**Comment by bpoldrack** [comment] 2023-04-12 09:39
I don't think the issue and best solution is currently fully understood.

**Comment by loj** [comment] 2023-04-14 09:51
Closing, as I believe this is a duplicate of #3. Please reopen if you disagree.

**Closed by loj** 2023-04-14 09:51 UTC
Labels: support-tracker
